spring.application.name=OnlineOrders

spring.profiles.active = dev

#Cambiar los nombres de mio1 y mio2 a import y data respectivamente para el perfil dev
#Cambiar los nombres de import y data a mio1 y mio2 respectivamente para el perfil test