# Configura P6Spy para utilizar el driver de PostgreSQL
realdriver=org.postgresql.Driver

# Configura el log para P6Spy
#appender=com.p6spy.engine.spy.appender.Slf4JLogger
logMessageFormat=com.p6spy.engine.spy.appender.MultiLineFormat
include=true

# Opcional: guarda los logs en un archivo
appender=com.p6spy.engine.spy.appender.FileLogger
logfile=logs/p6spy.log