/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import org.openapitools.client.model.OrdineDto;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for BillDto
 */
class BillDtoTest {
    private final BillDto model = new BillDto();

    /**
     * Model tests for BillDto
     */
    @Test
    void testBillDto() {
        // TODO: test BillDto
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'dateBill'
     */
    @Test
    void dateBillTest() {
        // TODO: test dateBill
    }

    /**
     * Test the property 'totalAmount'
     */
    @Test
    void totalAmountTest() {
        // TODO: test totalAmount
    }

    /**
     * Test the property 'ord'
     */
    @Test
    void ordTest() {
        // TODO: test ord
    }

}
