/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.ClientDto;
import org.openapitools.client.model.ProductDto;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for OrdineDto
 */
class OrdineDtoTest {
    private final OrdineDto model = new OrdineDto();

    /**
     * Model tests for OrdineDto
     */
    @Test
    void testOrdineDto() {
        // TODO: test OrdineDto
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'dateOrdine'
     */
    @Test
    void dateOrdineTest() {
        // TODO: test dateOrdine
    }

    /**
     * Test the property 'total'
     */
    @Test
    void totalTest() {
        // TODO: test total
    }

    /**
     * Test the property 'cli'
     */
    @Test
    void cliTest() {
        // TODO: test cli
    }

    /**
     * Test the property 'prods'
     */
    @Test
    void prodsTest() {
        // TODO: test prods
    }

}
