/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.model.ClientDto;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for ClientApi
 */
@Disabled
public class ClientApiTest {

    private final ClientApi api = new ClientApi();

    
    /**
     * Delete a client
     *
     * Delete a client by a specific id from the list of clients in the data source
     */
    @Test
    public void deleteClientTest()  {
        // uncomment below to test the function
        //Long id = null;
        //api.deleteClient(id).block();

        // TODO: test validations
    }
    
    /**
     * Fetch all clients
     *
     * Fetches all clients entities and their data from data source
     */
    @Test
    public void getAllClientsTest()  {
        // uncomment below to test the function
        //List<ClientDto> response = api.getAllClients().collectList().block();

        // TODO: test validations
    }
    
    /**
     * Fetch a client by Id
     *
     * Fetches a client entity and their data from data source by an specific Id
     */
    @Test
    public void getClientByIdTest()  {
        // uncomment below to test the function
        //Long id = null;
        //ClientDto response = api.getClientById(id).block();

        // TODO: test validations
    }
    
    /**
     * Adds a client
     *
     * Adds a client to the list of clients in the data source
     */
    @Test
    public void saveClientTest()  {
        // uncomment below to test the function
        //ClientDto clientDto = null;
        //ClientDto response = api.saveClient(clientDto).block();

        // TODO: test validations
    }
    
    /**
     * Update a client
     *
     * Update a client by a specific id from the list of clients in the data source
     */
    @Test
    public void updateClientTest()  {
        // uncomment below to test the function
        //ClientDto clientDto = null;
        //ClientDto response = api.updateClient(clientDto).block();

        // TODO: test validations
    }
    
}
