/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.model.OrdineDto;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for OrdineApi
 */
@Disabled
public class OrdineApiTest {

    private final OrdineApi api = new OrdineApi();

    
    /**
     * Delete a ordine
     *
     * Delete a ordine by a specific id from the list of ordini in the data source
     */
    @Test
    public void deleteOrdineTest()  {
        // uncomment below to test the function
        //Long id = null;
        //api.deleteOrdine(id).block();

        // TODO: test validations
    }
    
    /**
     * Fetch all ordini
     *
     * Fetches all ordini entities and their data from data source
     */
    @Test
    public void getAllOrdiniTest()  {
        // uncomment below to test the function
        //List<OrdineDto> response = api.getAllOrdini().collectList().block();

        // TODO: test validations
    }
    
    /**
     * Fetch a ordine by Id
     *
     * Fetches a ordine entity and their data from data source by an specific Id
     */
    @Test
    public void getOrdineByIdTest()  {
        // uncomment below to test the function
        //Long id = null;
        //OrdineDto response = api.getOrdineById(id).block();

        // TODO: test validations
    }
    
    /**
     * Adds a ordine
     *
     * Adds a ordine to the list of ordini in the data source
     */
    @Test
    public void saveOrdineTest()  {
        // uncomment below to test the function
        //OrdineDto ordineDto = null;
        //OrdineDto response = api.saveOrdine(ordineDto).block();

        // TODO: test validations
    }
    
    /**
     * Update a ordine
     *
     * Update a ordine by a specific id from the list of ordini in the data source
     */
    @Test
    public void updateOrdineTest()  {
        // uncomment below to test the function
        //OrdineDto ordineDto = null;
        //OrdineDto response = api.updateOrdine(ordineDto).block();

        // TODO: test validations
    }
    
}
